Repository softeerbootcamp4th/Team2-TiramisuCake-BE, pull requests merged in 2024-08, with the labels that each got.

#29 [Refactor] 공유 url 기능 관련 수정
  src/main/java/com/softeer/backend/fo_domain/share/controller/ShareInfoController.java
  src/main/java/com/softeer/backend/fo_domain/share/domain/ShareInfo.java
  src/main/java/com/softeer/backend/fo_domain/share/exception/ShareInfoException.java
  src/main/java/com/softeer/backend/fo_domain/share/repository/ShareInfoRepository.java
  src/main/java/com/softeer/backend/fo_domain/share/service/ShareInfoService.java
  src/main/java/com/softeer/backend/global/common/code/status/ErrorStatus.java
  src/main/java/com/softeer/backend/global/util/SharedUrlUtil.java
Labels: Refactor, BE

#31 [Feat] 복권 이벤트 페이지 접속 API 구현
  .gitignore
  build.gradle
  src/main/java/com/softeer/backend/fo_domain/draw/controller/DrawController.java
  src/main/java/com/softeer/backend/fo_domain/draw/domain/Draw.java
  src/main/java/com/softeer/backend/fo_domain/draw/domain/DrawParticipationInfo.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/DrawResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/exception/DrawException.java
  src/main/java/com/softeer/backend/fo_domain/draw/repository/DrawParticipationInfoRepository.java
  src/main/java/com/softeer/backend/fo_domain/draw/repository/DrawRepository.java
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawService.java
  src/main/java/com/softeer/backend/fo_domain/share/domain/ShareInfo.java
  src/main/java/com/softeer/backend/fo_domain/share/repository/ShareInfoRepository.java
  src/main/java/com/softeer/backend/global/common/code/status/ErrorStatus.java
Labels: Feat, BE

#39 [Infra] CI/CD 구축
  .github/workflows/deploy.yml
  appspec.yml
  scripts/after-install.sh
  src/main/java/com/softeer/backend/fo_domain/draw/domain/Draw.java
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawService.java
Labels: Infra, BE

#40 [Feat] 로그인 API 구현
  src/main/java/com/softeer/backend/fo_domain/user/controller/LoginController.java
  src/main/java/com/softeer/backend/fo_domain/user/domain/User.java
  src/main/java/com/softeer/backend/fo_domain/user/dto/LoginRequest.java
  src/main/java/com/softeer/backend/fo_domain/user/repository/UserRepository.java
  src/main/java/com/softeer/backend/fo_domain/user/service/LoginService.java
  src/main/java/com/softeer/backend/global/common/code/status/ErrorStatus.java
  src/main/java/com/softeer/backend/global/common/code/status/SuccessStatus.java
  src/test/java/com/softeer/backend/BackendApplicationTests.java
Labels: Feat, BE

#46 [Infra] pull_request시 Github Actions 동작하도록 수정
  .github/workflows/deploy.yml
Labels: Refactor, Infra, BE

#57 [Feat] 기대평 기능 구현
  build.gradle
  src/main/java/com/softeer/backend/fo_domain/comment/constant/CommentNickname.java
  src/main/java/com/softeer/backend/fo_domain/comment/constant/ExpectationComment.java
  src/main/java/com/softeer/backend/fo_domain/comment/controller/CommentController.java
  src/main/java/com/softeer/backend/fo_domain/comment/converter/ExpectationCommentConverter.java
  src/main/java/com/softeer/backend/fo_domain/comment/domain/Comment.java
  src/main/java/com/softeer/backend/fo_domain/comment/dto/CommentsResponse.java
  src/main/java/com/softeer/backend/fo_domain/comment/exception/CommentException.java
  src/main/java/com/softeer/backend/fo_domain/comment/repository/CommentRepository.java
  src/main/java/com/softeer/backend/fo_domain/comment/service/CommentService.java
  src/main/java/com/softeer/backend/fo_domain/comment/util/ScrollPaginationUtil.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/domain/Fcfs.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsService.java
  src/main/java/com/softeer/backend/fo_domain/user/controller/LoginController.java
  src/main/java/com/softeer/backend/fo_domain/user/dto/LoginRequest.java
  src/main/java/com/softeer/backend/fo_domain/user/dto/UserTokenResponse.java
  src/main/java/com/softeer/backend/fo_domain/user/service/LoginService.java
  src/main/java/com/softeer/backend/global/annotation/argumentresolver/AuthInfoArgumentResolver.java
  src/main/java/com/softeer/backend/global/common/code/status/ErrorStatus.java
  src/main/java/com/softeer/backend/global/common/code/status/SuccessStatus.java
  src/main/java/com/softeer/backend/global/common/constant/RedisLockPrefix.java
  src/main/java/com/softeer/backend/global/common/entity/BaseEntity.java
  src/main/java/com/softeer/backend/global/filter/JwtAuthenticationFilter.java
  src/main/java/com/softeer/backend/global/util/JwtUtil.java
Labels: Feat, BE

#59 [Feat] 추첨 페이지 접속 api 구현
  src/main/java/com/softeer/backend/fo_domain/draw/domain/DrawSetting.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/DrawLoseResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/DrawResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/DrawWinResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/LoseModal.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/WinModal.java
  src/main/java/com/softeer/backend/fo_domain/draw/repository/DrawSettingRepository.java
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawService.java
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawSettingManager.java
  src/main/java/com/softeer/backend/fo_domain/draw/util/DrawUtil.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsService.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsSettingManager.java
  src/main/java/com/softeer/backend/fo_domain/share/domain/ShareUrlInfo.java
  src/main/java/com/softeer/backend/fo_domain/share/exception/ShareUrlInfoException.java
  src/main/java/com/softeer/backend/fo_domain/share/repository/ShareUrlInfoRepository.java
  src/main/java/com/softeer/backend/global/common/constant/RedisLockPrefix.java
  src/main/java/com/softeer/backend/global/config/schedular/SchedularConfig.java
  src/main/java/com/softeer/backend/global/util/EventLockRedisUtil.java
Labels: Feat, BE

#67 [Feat]Admin Api 구현
  build.gradle
  src/main/java/com/softeer/backend/bo_domain/admin/controller/AdminLoginController.java
  src/main/java/com/softeer/backend/bo_domain/admin/controller/EventPageController.java
  src/main/java/com/softeer/backend/bo_domain/admin/controller/IndicatorPageController.java
  src/main/java/com/softeer/backend/bo_domain/admin/controller/MainPageController.java
  src/main/java/com/softeer/backend/bo_domain/admin/controller/WinnerPageController.java
  src/main/java/com/softeer/backend/bo_domain/admin/domain/Admin.java
  src/main/java/com/softeer/backend/bo_domain/admin/dto/event/DrawEventTimeRequestDto.java
  src/main/java/com/softeer/backend/bo_domain/admin/dto/event/FcfsEventTimeRequestDto.java
  src/main/java/com/softeer/backend/bo_domain/admin/dto/indicator/EventIndicatorResponseDto.java
  src/main/java/com/softeer/backend/bo_domain/admin/dto/login/AdminLoginRequestDto.java
  src/main/java/com/softeer/backend/bo_domain/admin/dto/main/MainPageResponseDto.java
  src/main/java/com/softeer/backend/bo_domain/admin/dto/winner/DrawWinnerListResponseDto.java
  src/main/java/com/softeer/backend/bo_domain/admin/dto/winner/DrawWinnerUpdateRequestDto.java
  src/main/java/com/softeer/backend/bo_domain/admin/dto/winner/FcfsWinnerListResponseDto.java
  src/main/java/com/softeer/backend/bo_domain/admin/dto/winner/FcfsWinnerUpdateRequestDto.java
  src/main/java/com/softeer/backend/bo_domain/admin/exception/AdminException.java
  src/main/java/com/softeer/backend/bo_domain/admin/repository/AdminRepository.java
  src/main/java/com/softeer/backend/bo_domain/admin/serializer/PercentageSerializer.java
  src/main/java/com/softeer/backend/bo_domain/admin/serializer/PhoneNumberSerializer.java
  src/main/java/com/softeer/backend/bo_domain/admin/service/AdminLoginService.java
  src/main/java/com/softeer/backend/bo_domain/admin/service/EventPageService.java
  src/main/java/com/softeer/backend/bo_domain/admin/service/IndicatorPageService.java
  src/main/java/com/softeer/backend/bo_domain/admin/service/MainPageService.java
  src/main/java/com/softeer/backend/bo_domain/admin/service/WinnerPageService.java
  src/main/java/com/softeer/backend/bo_domain/admin/util/PasswordEncoder.java
  src/main/java/com/softeer/backend/bo_domain/admin/validator/DrawTimeRangeValidator.java
  src/main/java/com/softeer/backend/bo_domain/admin/validator/FcfsDateRangeValidator.java
  src/main/java/com/softeer/backend/bo_domain/admin/validator/FcfsTimeRangeValidator.java
  src/main/java/com/softeer/backend/bo_domain/admin/validator/annotation/ValidDrawTimeRange.java
  src/main/java/com/softeer/backend/bo_domain/admin/validator/annotation/ValidFcfsDateRange.java
  src/main/java/com/softeer/backend/bo_domain/admin/validator/annotation/ValidFcfsTimeRange.java
  src/main/java/com/softeer/backend/bo_domain/eventparticipation/domain/EventParticipation.java
  src/main/java/com/softeer/backend/bo_domain/eventparticipation/repository/EventParticipationRepository.java
  src/main/java/com/softeer/backend/fo_domain/comment/service/CommentService.java
  src/main/java/com/softeer/backend/fo_domain/draw/domain/Draw.java
  src/main/java/com/softeer/backend/fo_domain/draw/domain/DrawSetting.java
  src/main/java/com/softeer/backend/fo_domain/draw/repository/DrawRepository.java
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawSettingManager.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/domain/FcfsSetting.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/repository/FcfsRepository.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsSettingManager.java
  src/main/java/com/softeer/backend/fo_domain/user/controller/LoginController.java
  src/main/java/com/softeer/backend/fo_domain/user/service/LoginService.java
  src/main/java/com/softeer/backend/global/annotation/argumentresolver/AuthInfoArgumentResolver.java
  src/main/java/com/softeer/backend/global/common/code/status/SuccessStatus.java
  src/main/java/com/softeer/backend/global/common/constant/ValidationConstant.java
  src/main/java/com/softeer/backend/global/common/dto/JwtClaimsDto.java
  src/main/java/com/softeer/backend/global/common/dto/JwtTokenResponseDto.java
  src/main/java/com/softeer/backend/global/filter/JwtAuthenticationFilter.java
  src/main/java/com/softeer/backend/global/filter/JwtAuthorizationFilter.java
  src/main/java/com/softeer/backend/global/util/JwtUtil.java
  src/main/java/com/softeer/backend/global/util/StringRedisUtil.java
Labels: Config, Feat, BE

#70 [Refactor] 공유 url 조회하는 api 수정
  build.gradle
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawService.java
  src/main/java/com/softeer/backend/fo_domain/share/repository/ShareInfoRepository.java
  src/main/java/com/softeer/backend/fo_domain/share/service/ShareInfoService.java
  src/main/java/com/softeer/backend/fo_domain/user/dto/LoginRequestDto.java
Labels: Refactor, BE

#71 [Feature] static text를 관리하는 enum 구현
  src/main/java/com/softeer/backend/bo_domain/admin/controller/AdminMainPageController.java
  src/main/java/com/softeer/backend/bo_domain/admin/controller/WinnerPageController.java
  src/main/java/com/softeer/backend/bo_domain/admin/dto/winner/DrawWinnerUpdateRequestDto.java
  src/main/java/com/softeer/backend/bo_domain/admin/dto/winner/FcfsWinnerUpdateRequestDto.java
  src/main/java/com/softeer/backend/bo_domain/admin/service/EventPageService.java
  src/main/java/com/softeer/backend/bo_domain/admin/validator/FcfsDateRangeValidator.java
  src/main/java/com/softeer/backend/fo_domain/comment/constant/ExpectationComment.java
  src/main/java/com/softeer/backend/fo_domain/comment/controller/CommentController.java
  src/main/java/com/softeer/backend/fo_domain/comment/service/CommentService.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/controller/MainPageController.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/service/MainPageService.java
  src/main/java/com/softeer/backend/fo_domain/user/service/LoginService.java
  src/main/java/com/softeer/backend/global/common/constant/ValidationConstant.java
  src/main/java/com/softeer/backend/global/common/exception/ExceptionAdvice.java
  src/main/java/com/softeer/backend/global/staticresources/constant/StaticText.java
  src/main/java/com/softeer/backend/global/staticresources/domain/StaticResources.java
  src/main/java/com/softeer/backend/global/staticresources/repository/StaticResourcesRepository.java
  src/main/java/com/softeer/backend/global/staticresources/util/StaticResourcesUtil.java
Labels: Feat, BE

#72 [Refactor] MainPageController 클래스명 변경
  src/main/java/com/softeer/backend/bo_domain/admin/controller/AdminMainPageController.java
  src/main/java/com/softeer/backend/bo_domain/admin/service/AdminMainPageService.java
  src/main/java/com/softeer/backend/global/staticresources/util/StaticResourcesUtil.java
Labels: Refactor, BE

#73 [Feature] 메인 페이지 GET API 구현하기
  src/main/java/com/softeer/backend/bo_domain/admin/controller/AdminMainPageController.java
  src/main/java/com/softeer/backend/bo_domain/admin/dto/main/AdminMainPageResponseDto.java
  src/main/java/com/softeer/backend/bo_domain/admin/dto/winner/FcfsWinnerUpdateRequestDto.java
  src/main/java/com/softeer/backend/bo_domain/admin/service/AdminMainPageService.java
  src/main/java/com/softeer/backend/bo_domain/admin/service/WinnerPageService.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/controller/MainPageController.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/dto/MainPageCarResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/dto/MainPageEventResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/service/MainPageService.java
  src/main/java/com/softeer/backend/global/filter/JwtAuthenticationFilter.java
  src/main/java/com/softeer/backend/global/staticresources/constant/StaticText.java
  src/main/java/com/softeer/backend/global/staticresources/util/StaticResourcesUtil.java
Labels: Feat, BE

#78 [Refactor] 사용자 생성 시 추첨 참여 정보, 공유 링크 정보, 공유 정보 생성
  build.gradle
  src/main/java/com/softeer/backend/fo_domain/share/domain/ShareUrlInfo.java
  src/main/java/com/softeer/backend/fo_domain/share/repository/ShareUrlInfoRepository.java
  src/main/java/com/softeer/backend/fo_domain/user/dto/LoginRequestDto.java
Labels: Refactor, BE

#81 [Fix] Car 페이지 정보를 반환하는 메서드 수정
  src/main/java/com/softeer/backend/fo_domain/mainpage/service/MainPageService.java
Labels: BE, Fix

#87 [Refactor]기대평 댓글을 typeId로 관리 및 메인페이지 Dto 변경
  src/main/java/com/softeer/backend/fo_domain/comment/constant/ExpectationComment.java
  src/main/java/com/softeer/backend/fo_domain/comment/controller/CommentController.java
  src/main/java/com/softeer/backend/fo_domain/comment/converter/ExpectationCommentConverter.java
  src/main/java/com/softeer/backend/fo_domain/comment/domain/Comment.java
  src/main/java/com/softeer/backend/fo_domain/comment/dto/CommentsResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/comment/service/CommentService.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/dto/MainPageEventResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/service/MainPageService.java
  src/main/java/com/softeer/backend/global/staticresources/constant/StaticText.java
  src/main/java/com/softeer/backend/global/staticresources/util/StaticResourcesUtil.java
Labels: Refactor, BE

#88 [Refactor] Comment entity의 @column name 속성 변경
  src/main/java/com/softeer/backend/fo_domain/comment/domain/Comment.java
Labels: Refactor, BE

#94 [Feat] 공유 url 반환 api 구현
  src/main/java/com/softeer/backend/fo_domain/share/controller/ShareController.java
  src/main/java/com/softeer/backend/fo_domain/share/dto/ShareUrlInfoResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/share/dto/ShareUrlResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/share/service/ShareInfoService.java
  src/main/java/com/softeer/backend/fo_domain/share/service/ShareUrlInfoService.java
  src/main/java/com/softeer/backend/global/filter/JwtAuthenticationFilter.java
  src/main/java/com/softeer/backend/global/staticresources/constant/StaticText.java
Labels: Refactor, Feat, BE

#96 [Feat] 댓글 조회시 댓글 순서를 반대로 보내기
  src/main/java/com/softeer/backend/fo_domain/comment/repository/CommentRepository.java
  src/main/java/com/softeer/backend/fo_domain/comment/service/CommentService.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/dto/MainPageEventResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/service/MainPageService.java
  src/main/java/com/softeer/backend/global/staticresources/constant/StaticText.java
Labels: Feat, BE

#99 [Feat] 이벤트 속성값이 변경되면 이벤트 환경설정 manager 클래스의 값을 직접 바꾸는 기능 구현
  src/main/java/com/softeer/backend/bo_domain/admin/controller/IndicatorPageController.java
  src/main/java/com/softeer/backend/bo_domain/admin/dto/event/EventPageResponseDto.java
  src/main/java/com/softeer/backend/bo_domain/admin/dto/winner/WinnerPageResponseDto.java
  src/main/java/com/softeer/backend/bo_domain/admin/service/EventPageService.java
  src/main/java/com/softeer/backend/bo_domain/admin/service/IndicatorPageService.java
  src/main/java/com/softeer/backend/bo_domain/admin/service/WinnerPageService.java
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawSettingManager.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/controller/FcfsController.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/dto/FcfsSettingDto.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsService.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsSettingManager.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/service/MainPageService.java
  src/main/java/com/softeer/backend/global/staticresources/util/StaticResourcesUtil.java
Labels: Feat, BE

#100 [Feat] 메인페이지 방문자 수 관리하는 기능 구현
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawService.java
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawSettingManager.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsService.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsSettingManager.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/service/MainPageService.java
  src/main/java/com/softeer/backend/global/common/constant/RedisKeyPrefix.java
  src/main/java/com/softeer/backend/global/config/schedular/SchedulerConfig.java
  src/main/java/com/softeer/backend/global/scheduler/DbInsertScheduler.java
  src/main/java/com/softeer/backend/global/util/EventLockRedisUtil.java
Labels: Feat, BE

#102 [Feat] 추첨 이벤트 참여 api 작성
  scripts/after-install.sh
  src/main/java/com/softeer/backend/fo_domain/draw/controller/DrawController.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/DrawLoseFullAttendResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/DrawLoseNotAttendResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/DrawLoseResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/DrawWinNotAttendResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/main/DrawMainFullAttendResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/main/DrawMainResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/participate/DrawLoseModalResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/participate/DrawModalResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/participate/DrawWinModalResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawService.java
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawSettingManager.java
  src/main/java/com/softeer/backend/fo_domain/draw/util/DrawUtil.java
  src/main/java/com/softeer/backend/global/common/constant/RedisKeyPrefix.java
  src/main/java/com/softeer/backend/global/staticresources/constant/StaticText.java
Labels: Refactor, Feat, BE

#104 [Refactor] JWT 만료시간 형식 수정
  src/main/java/com/softeer/backend/global/common/dto/JwtTokenResponseDto.java
Labels: Refactor, BE

#108 [Fix] ci/cd 오류 해결
  src/main/java/com/softeer/backend/bo_domain/admin/controller/AdminLoginController.java
  src/main/java/com/softeer/backend/fo_domain/comment/controller/CommentController.java
  src/main/java/com/softeer/backend/fo_domain/draw/controller/DrawController.java
  src/main/java/com/softeer/backend/fo_domain/share/controller/ShareController.java
Labels: BE, Fix

#109 [Fix] 이전 커밋으로 revert
  src/main/java/com/softeer/backend/bo_domain/admin/dto/indicator/EventIndicatorResponseDto.java
  src/main/java/com/softeer/backend/bo_domain/admin/service/IndicatorPageService.java
  src/main/java/com/softeer/backend/bo_domain/eventparticipation/domain/EventParticipation.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/controller/FcfsController.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/domain/Quiz.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/dto/FcfsFailResponseDtoDto.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/dto/FcfsPageResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/dto/FcfsResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/dto/FcfsSuccessResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/dto/QuizDto.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/dto/result/FcfsFailResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/dto/result/FcfsResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/dto/result/FcfsSuccessResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/exception/FcfsException.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/interceptor/FcfsTimeCheckInterceptor.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/repository/FcfsSettingRepository.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/repository/QuizRepository.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsService.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsSettingManager.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/dto/MainPageEventResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/service/MainPageService.java
  src/main/java/com/softeer/backend/global/common/exception/ExceptionAdvice.java
  src/main/java/com/softeer/backend/global/config/web/WebMvcConfig.java
  src/main/java/com/softeer/backend/global/staticresources/constant/StaticText.java
  src/main/java/com/softeer/backend/global/staticresources/util/StaticResourcesUtil.java
Labels: BE, Fix

#111 [Feat] 추첨 결과 재확인 api 구현
  src/main/java/com/softeer/backend/fo_domain/draw/controller/DrawController.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/result/DrawHistoryLoserResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/result/DrawHistoryResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/result/DrawHistoryWinnerResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawService.java
  src/main/java/com/softeer/backend/fo_domain/draw/util/DrawUtil.java
Labels: Feat, BE

#113 [Feat] 선착순 기능 구현
  src/main/java/com/softeer/backend/bo_domain/admin/service/EventPageService.java
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawSettingManager.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/controller/FcfsController.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/domain/Fcfs.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/interceptor/FcfsTimeCheckInterceptor.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsService.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsSettingManager.java
  src/main/java/com/softeer/backend/global/common/constant/RedisKeyPrefix.java
  src/main/java/com/softeer/backend/global/common/exception/ExceptionAdvice.java
  src/main/java/com/softeer/backend/global/config/redis/RedisConfig.java
  src/main/java/com/softeer/backend/global/config/web/WebMvcConfig.java
  src/main/java/com/softeer/backend/global/scheduler/DbInsertScheduler.java
  src/main/java/com/softeer/backend/global/util/FcfsRedisUtil.java
Labels: Feat, BE

#115 [Refactor] 선착순 예외 응답 변경
  src/main/java/com/softeer/backend/fo_domain/fcfs/controller/FcfsController.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/dto/result/FcfsFailResult.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/dto/result/FcfsResult.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/dto/result/FcfsResultResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/dto/result/FcfsSuccessResult.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsService.java
  src/main/java/com/softeer/backend/global/util/JwtUtil.java
Labels: Refactor, BE

#118 [Feat] 공유 url을 이용해 인증했을 때 공유한 사용자의 추첨 기회 증가하는 로직 구현
  src/main/java/com/softeer/backend/fo_domain/share/controller/ShareController.java
  src/main/java/com/softeer/backend/fo_domain/share/repository/ShareInfoRepository.java
  src/main/java/com/softeer/backend/fo_domain/share/repository/ShareUrlInfoRepository.java
  src/main/java/com/softeer/backend/fo_domain/user/controller/LoginController.java
  src/main/java/com/softeer/backend/fo_domain/user/service/LoginService.java
  src/main/java/com/softeer/backend/global/filter/JwtAuthenticationFilter.java
  src/main/java/com/softeer/backend/global/staticresources/constant/StaticText.java
Labels: Feat, BE

#120 [Refactor] 데이터베이스 업데이트하는 로직 쿼리 사용하도록 리팩토링
  src/main/java/com/softeer/backend/fo_domain/draw/repository/DrawParticipationInfoRepository.java
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawService.java
  src/main/java/com/softeer/backend/fo_domain/share/repository/ShareInfoRepository.java
Labels: Refactor, BE

#123 [Fix] 퀴즈 정답 문자열 변형 해결 및 swagger AccessToken에 자동으로 Bearer붙여주는 설정
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsSettingManager.java
  src/main/java/com/softeer/backend/global/config/docs/SwaggerConfig.java
Labels: Refactor, BE, Fix

#129 [Refactor] 추첨 서비스 리팩토링
  src/main/java/com/softeer/backend/fo_domain/draw/controller/DrawController.java
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawService.java
  src/main/java/com/softeer/backend/fo_domain/draw/util/DrawModalGenerateUtil.java
  src/main/java/com/softeer/backend/fo_domain/draw/util/DrawResponseGenerateUtil.java
  src/main/java/com/softeer/backend/fo_domain/draw/util/DrawUtil.java
  src/main/java/com/softeer/backend/fo_domain/share/controller/ShareController.java
  src/main/java/com/softeer/backend/fo_domain/share/service/ShareUrlInfoService.java
  src/main/java/com/softeer/backend/fo_domain/user/service/LoginService.java
  src/main/java/com/softeer/backend/global/util/DrawRedisUtil.java
Labels: Refactor, BE

#132 [Fix] redirect 시, code값 null 나오는 문제 수정중 2
  src/main/java/com/softeer/backend/fo_domain/fcfs/controller/FcfsController.java
  src/main/java/com/softeer/backend/fo_domain/user/controller/LoginController.java
  src/main/java/com/softeer/backend/global/config/docs/SwaggerConfig.java
Labels: BE, Fix

#133 [Feat] 다음 선착순 이벤트 시작시간을 보내주는 기능 구현
  src/main/java/com/softeer/backend/fo_domain/fcfs/controller/FcfsController.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsSettingManager.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/dto/MainPageEventResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/service/MainPageService.java
Labels: Feat, BE

#134 [Fix] redirect 시, code값 null 나오는 문제 수정중 3
  src/main/java/com/softeer/backend/fo_domain/fcfs/controller/FcfsController.java
Labels: BE, Fix

#140 [Refactor] 공유 url의 BASE URL 변경
  src/main/java/com/softeer/backend/fo_domain/share/controller/ShareController.java
  src/main/java/com/softeer/backend/global/staticresources/constant/StaticText.java
Labels: Refactor, BE

#143 [Refactor] 공유 url의 path 변경
  src/main/java/com/softeer/backend/global/staticresources/constant/StaticText.java
Labels: Refactor, BE

#146 [Refactor] 공유 url의 쿠키 변경
  src/main/java/com/softeer/backend/fo_domain/share/controller/ShareController.java
  src/main/java/com/softeer/backend/global/staticresources/constant/StaticText.java
Labels: Refactor, BE

#148 [Refactor] 추첨 서비스 리팩토링 2
  src/main/java/com/softeer/backend/fo_domain/draw/dto/main/DrawMainFullAttendResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/modal/WinModal.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/participate/DrawWinModalResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/result/DrawHistoryWinnerResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/util/DrawModalGenerateUtil.java
  src/main/java/com/softeer/backend/fo_domain/draw/util/DrawResponseGenerateUtil.java
Labels: Refactor, BE

#151 [Feat] 추첨 이벤트 연속 출석 관리 로직 추가
  src/main/java/com/softeer/backend/fo_domain/draw/domain/DrawParticipationInfo.java
  src/main/java/com/softeer/backend/fo_domain/draw/repository/DrawParticipationInfoRepository.java
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawService.java
  src/main/java/com/softeer/backend/fo_domain/user/service/LoginService.java
Labels: Feat, BE

#152 [Fix] 기대평을 조회할 때 최신 댓글이 먼저 조회되지 않는 문제 2
  src/main/java/com/softeer/backend/fo_domain/comment/service/CommentService.java
Labels: BE, Fix

#153 [Fix] 최신 기대평이 조회되지 않는 문제 해결
  src/main/java/com/softeer/backend/fo_domain/comment/repository/CommentRepository.java
  src/main/java/com/softeer/backend/fo_domain/comment/service/CommentService.java
  src/main/java/com/softeer/backend/fo_domain/comment/util/ScrollPaginationUtil.java
Labels: BE, Fix

#156 [Test] DrawService의 테스트코드 작성
  build.gradle
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawService.java
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawSettingManager.java
  src/main/java/com/softeer/backend/fo_domain/draw/util/DrawAttendanceCountUtil.java
  src/main/java/com/softeer/backend/fo_domain/share/repository/ShareInfoRepository.java
  src/main/java/com/softeer/backend/fo_domain/user/service/LoginService.java
  src/main/java/com/softeer/backend/global/scheduler/DbInsertScheduler.java
  src/main/java/com/softeer/backend/global/util/DrawRedisUtil.java
  src/test/java/com/softeer/backend/fo_domain/draw/service/DrawServiceTest.java
Labels: Test, Refactor, BE

#157 [Feat] 공유 url의 BASE URL 변경
  src/main/java/com/softeer/backend/fo_domain/draw/dto/main/DrawMainResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/util/DrawResponseGenerateUtil.java
  src/main/java/com/softeer/backend/fo_domain/share/service/ShareUrlInfoService.java
  src/main/java/com/softeer/backend/fo_domain/user/controller/LoginController.java
  src/main/java/com/softeer/backend/fo_domain/user/service/LoginService.java
Labels: Feat, BE

#161 [Feat] 정적 파일 캐싱하기
  build.gradle
  src/main/java/com/softeer/backend/BackendApplication.java
  src/main/java/com/softeer/backend/bo_domain/admin/serializer/PhoneNumberSerializer.java
  src/main/java/com/softeer/backend/fo_domain/draw/util/DrawModalGenerateUtil.java
  src/main/java/com/softeer/backend/fo_domain/draw/util/DrawResponseGenerateUtil.java
  src/main/java/com/softeer/backend/fo_domain/draw/util/DrawUtil.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/controller/FcfsController.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/dto/result/FcfsSuccessResult.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsService.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/controller/MainPageController.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/dto/MainPageEventInfoResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/dto/MainPageEventStaticResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/service/MainPageService.java
  src/main/java/com/softeer/backend/fo_domain/share/service/ShareUrlInfoService.java
  src/main/java/com/softeer/backend/global/common/constant/RedisKeyPrefix.java
  src/main/java/com/softeer/backend/global/config/cache/CacheConfig.java
  src/main/java/com/softeer/backend/global/config/web/WebMvcConfig.java
  src/main/java/com/softeer/backend/global/filter/JwtAuthenticationFilter.java
  src/main/java/com/softeer/backend/global/staticresources/constant/S3FileName.java
  src/main/java/com/softeer/backend/global/staticresources/constant/StaticText.java
  src/main/java/com/softeer/backend/global/staticresources/constant/StaticTextName.java
  src/main/java/com/softeer/backend/global/staticresources/domain/S3Content.java
  src/main/java/com/softeer/backend/global/staticresources/domain/TextContent.java
  src/main/java/com/softeer/backend/global/staticresources/repository/S3ContentRepository.java
  src/main/java/com/softeer/backend/global/staticresources/repository/StaticResourcesRepository.java
  src/main/java/com/softeer/backend/global/staticresources/repository/TextContentRepository.java
  src/main/java/com/softeer/backend/global/staticresources/util/StaticResourceUtil.java
  src/main/java/com/softeer/backend/global/staticresources/util/StaticResourcesUtil.java
Labels: Feat, BE

#163 [Fix] 분산락 Aop 적용 시 작동하지 않던 문제 해결
  src/main/java/com/softeer/backend/global/common/constant/RedisKeyPrefix.java
  src/main/java/com/softeer/backend/global/util/DrawRedisUtil.java
  src/main/java/com/softeer/backend/global/util/SpringELParser.java
Labels: Bug, BE, Fix

#164 이벤트 설정정보를 스케줄러로 가져오는 기능 구현
  src/main/java/com/softeer/backend/bo_domain/admin/dto/event/EventPageResponseDto.java
  src/main/java/com/softeer/backend/bo_domain/admin/dto/indicator/EventIndicatorResponseDto.java
  src/main/java/com/softeer/backend/bo_domain/admin/dto/winner/WinnerPageResponseDto.java
  src/main/java/com/softeer/backend/bo_domain/admin/service/EventPageService.java
  src/main/java/com/softeer/backend/bo_domain/admin/service/IndicatorPageService.java
  src/main/java/com/softeer/backend/bo_domain/admin/service/WinnerPageService.java
  src/main/java/com/softeer/backend/fo_domain/draw/domain/Draw.java
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawSettingManager.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsService.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsSettingManager.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/QuizManager.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/service/MainPageService.java
  src/main/java/com/softeer/backend/fo_domain/user/controller/VerificationController.java
  src/main/java/com/softeer/backend/fo_domain/user/domain/User.java
  src/main/java/com/softeer/backend/fo_domain/user/dto/verification/VerificationCodeTestResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/user/service/LoginService.java
  src/main/java/com/softeer/backend/fo_domain/user/service/VerificationService.java
  src/main/java/com/softeer/backend/global/common/code/status/ErrorStatus.java
  src/main/java/com/softeer/backend/global/config/redis/RedisConfig.java
  src/main/java/com/softeer/backend/global/config/schedular/SchedulerConfig.java
  src/main/java/com/softeer/backend/global/scheduler/DbInsertScheduler.java
  src/main/java/com/softeer/backend/global/scheduler/EventSettingScheduler.java
  src/main/java/com/softeer/backend/global/staticresources/util/StaticResourceUtil.java
Labels: Refactor, Feat, BE

#168 [Fix] 인증번호 인증 시, redis key에 대한 값에 접근 못하는 문제 해결
  src/main/java/com/softeer/backend/fo_domain/user/service/VerificationService.java
Labels: BE, Fix

#171 [Fix] Redis lock용 key와 데이터 접근용 key 분리
  src/main/java/com/softeer/backend/global/common/constant/RedisKeyPrefix.java
  src/main/java/com/softeer/backend/global/util/DrawRedisUtil.java
Labels: Bug, BE, Fix

#173 [Fix] Redis lock용 key와 선착순 당첨 유저Id 접근용 key의 혼용시 발생하는 에러 해결
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsService.java
  src/main/java/com/softeer/backend/global/common/constant/RedisKeyPrefix.java
  src/main/java/com/softeer/backend/global/scheduler/DbInsertScheduler.java
Labels: BE, Fix

#175 [Feat] 공유 url로 추첨 기회 추가하는 기능 구현
  src/main/java/com/softeer/backend/fo_domain/share/repository/ShareUrlInfoRepository.java
  src/main/java/com/softeer/backend/fo_domain/user/controller/LoginController.java
  src/main/java/com/softeer/backend/fo_domain/user/service/LoginService.java
  src/main/java/com/softeer/backend/global/config/web/WebMvcConfig.java
Labels: Feat, BE

#177 [Test] 기대평, 공유 url 테스트 코드 작성
  src/test/java/com/softeer/backend/fo_domain/comment/service/CommentServiceTest.java
  src/test/java/com/softeer/backend/fo_domain/share/service/ShareUrlInfoServiceTest.java
Labels: Test, BE

#180 [Fix] 추첨이벤트 참여 시 방향 이미지에 null 값이 들어가는 버그 수정
  src/main/java/com/softeer/backend/fo_domain/draw/util/DrawResponseGenerateUtil.java
  src/main/java/com/softeer/backend/fo_domain/draw/util/DrawUtil.java
Labels: Bug, BE, Fix

#182 [Feat] 당첨 내역 반환하는 api 구현
  src/main/java/com/softeer/backend/fo_domain/draw/controller/DrawController.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/history/DrawHistoryDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/history/DrawHistoryLoserResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/history/DrawHistoryResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/dto/history/DrawHistoryWinnerResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/draw/repository/DrawRepository.java
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawService.java
  src/main/java/com/softeer/backend/fo_domain/draw/util/DrawResponseGenerateUtil.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/controller/MainPageController.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/dto/MainPageEventStaticResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/service/MainPageService.java
  src/test/java/com/softeer/backend/fo_domain/draw/service/DrawServiceTest.java
Labels: Feat, BE

#186 [Feat] 메인페이지에서 경품 설명 반환하는 기능 추가
  src/main/java/com/softeer/backend/fo_domain/mainpage/controller/MainPageController.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/dto/MainPageEventStaticResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/service/MainPageService.java
  src/main/java/com/softeer/backend/global/staticresources/constant/StaticTextName.java
Labels: Feat, BE

#188 [Fix] 없는 공유 코드를 이용해 로그인을 시도할 경우 발생하는 오류 수정
  src/main/java/com/softeer/backend/fo_domain/draw/dto/history/DrawHistoryResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/user/service/LoginService.java
  src/test/java/com/softeer/backend/fo_domain/user/service/LoginServiceTest.java
Labels: Bug, BE, Fix

#189 [Feat] 선착순 당첨 내역을 조회하는 API 구현
  src/main/java/com/softeer/backend/fo_domain/fcfs/controller/FcfsController.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/domain/Fcfs.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/dto/FcfsHistoryResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/repository/FcfsRepository.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsService.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsSettingManager.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/QuizManager.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/dto/MainPageEventInfoResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/service/MainPageService.java
  src/main/java/com/softeer/backend/global/common/constant/RedisKeyPrefix.java
  src/main/java/com/softeer/backend/global/scheduler/DbInsertScheduler.java
  src/test/java/com/softeer/backend/bo_domain/admin/service/AdminLoginServiceTest.java
  src/test/java/com/softeer/backend/bo_domain/admin/service/EventPageServiceTest.java
  src/test/java/com/softeer/backend/bo_domain/admin/service/IndicatorPageServiceTest.java
  src/test/java/com/softeer/backend/bo_domain/admin/service/WinnerPageServiceTest.java
  src/test/java/com/softeer/backend/fo_domain/mainpage/service/MainPageServiceTest.java
Labels: Feat, BE

#191 [Feat] 선착순 이벤트의 시작 시간을 보내주는 기능 구현
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsSettingManager.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/service/MainPageService.java
  src/main/java/com/softeer/backend/global/filter/JwtAuthenticationFilter.java
  src/test/java/com/softeer/backend/fo_domain/mainpage/service/MainPageServiceTest.java
Labels: Feat, BE

#194 [Fix] 추첨이벤트 자잘한 로직 오류 수정
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawService.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/dto/MainPageEventInfoResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/service/MainPageService.java
  src/test/java/com/softeer/backend/fo_domain/draw/service/DrawServiceTest.java
  src/test/java/com/softeer/backend/fo_domain/mainpage/service/MainPageServiceTest.java
Labels: BE, Fix

#195 선착순 이벤트 종료 시, 응모를 시도하면 실패 모달정보를 보내주는 기능 구현
  src/main/java/com/softeer/backend/fo_domain/fcfs/controller/FcfsController.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/dto/result/FcfsResultResponseDto.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/interceptor/FcfsTimeCheckInterceptor.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsService.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/service/MainPageService.java
  src/main/java/com/softeer/backend/fo_domain/user/controller/LoginController.java
  src/main/java/com/softeer/backend/global/common/code/status/ErrorStatus.java
  src/main/java/com/softeer/backend/global/common/exception/ExceptionAdvice.java
  src/main/java/com/softeer/backend/global/staticresources/constant/StaticTextName.java
  src/test/java/com/softeer/backend/fo_domain/fcfs/service/FcfsServiceTest.java
Labels: Feat, BE

#201 [Feat] 테스트용 어드민 API 생성 2
  src/main/java/com/softeer/backend/bo_domain/admin/dto/FcfsSettingTestRequestDto.java
Labels: Feat, BE

#202 [Feat] 테스트용 어드민 API 생성 3
  src/main/java/com/softeer/backend/bo_domain/admin/dto/FcfsSettingTestRequestDto.java
  src/main/java/com/softeer/backend/global/filter/JwtAuthorizationFilter.java
Labels: Feat, BE

#205 [Feat] 어드민 로그인 및 회원가입 검증 기능 구현
  src/main/java/com/softeer/backend/bo_domain/admin/dto/login/AdminLoginRequestDto.java
  src/main/java/com/softeer/backend/bo_domain/admin/dto/login/AdminSignUpRequestDto.java
Labels: Feat, BE

#209 [Feat] 레디스 분산락 사용할 때 오류 발생하면 응답하는 로직 추가
  src/main/java/com/softeer/backend/global/common/exception/ExceptionAdvice.java
Labels: Feat, BE

#214 [Refactor] 어드민 로그인 제약조건 해제 2
  src/main/java/com/softeer/backend/bo_domain/admin/dto/login/AdminLoginRequestDto.java
Labels: Refactor, BE

#216 [Fix] 처음 로그인하고 추첨 페이지 접속했을 때 마지막 참여일자가 null로 반환되는 오류 수정
  src/main/java/com/softeer/backend/fo_domain/draw/util/DrawRemainDrawCountUtil.java
Labels: Bug, BE, Fix

#219 [Test] 비관적 락 테스트
  build.gradle
  scripts/after-install.sh
  src/main/java/com/softeer/backend/fo_domain/comment/controller/CommentController.java
  src/main/java/com/softeer/backend/fo_domain/comment/dto/CommentsResponsePageDto.java
  src/main/java/com/softeer/backend/fo_domain/comment/repository/CommentRepository.java
  src/main/java/com/softeer/backend/fo_domain/comment/service/CommentService.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/controller/FcfsController.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/domain/Fcfs.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/interceptor/FcfsTimeCheckInterceptor.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/repository/FcfsRepository.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsHandler/FcfsHandler.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsHandler/FcfsHandlerByLuaScript.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsHandler/FcfsHandlerByPessimisticLock.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsHandler/FcfsHandlerByRedisson.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsService.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/FcfsSettingManager.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/test/FcfsCount.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/test/FcfsCountRepository.java
  src/main/java/com/softeer/backend/fo_domain/fcfs/service/test/LuaRedisUtil.java
  src/main/java/com/softeer/backend/fo_domain/mainpage/service/MainPageService.java
  src/main/java/com/softeer/backend/global/annotation/EventLock.java
  src/main/java/com/softeer/backend/global/common/exception/ExceptionAdvice.java
  src/main/java/com/softeer/backend/global/config/redis/RedisConfig.java
  src/main/java/com/softeer/backend/global/filter/JwtAuthenticationFilter.java
  src/main/java/com/softeer/backend/global/scheduler/DbInsertScheduler.java
  src/main/java/com/softeer/backend/global/util/FcfsRedisUtil.java
  src/test/java/com/softeer/backend/bo_domain/admin/service/AdminLoginServiceTest.java
  src/test/java/com/softeer/backend/bo_domain/admin/service/EventPageServiceTest.java
  src/test/java/com/softeer/backend/bo_domain/admin/service/IndicatorPageServiceTest.java
  src/test/java/com/softeer/backend/bo_domain/admin/service/WinnerPageServiceTest.java
  src/test/java/com/softeer/backend/fo_domain/comment/service/CommentServiceTest.java
  src/test/java/com/softeer/backend/fo_domain/draw/service/DrawServiceTest.java
  src/test/java/com/softeer/backend/fo_domain/fcfs/service/FcfsServiceTest.java
  src/test/java/com/softeer/backend/fo_domain/mainpage/service/MainPageServiceTest.java
  src/test/java/com/softeer/backend/fo_domain/share/service/ShareUrlInfoServiceTest.java
  src/test/java/com/softeer/backend/fo_domain/user/service/LoginServiceTest.java
  src/test/java/com/softeer/backend/fo_domain/user/service/VerificationServiceTest.java
Labels: Test, BE

#221 [Fix] 당첨 로직 수정
  src/main/java/com/softeer/backend/fo_domain/draw/controller/DrawController.java
  src/main/java/com/softeer/backend/fo_domain/draw/lua/DrawRedisLua.java
  src/main/java/com/softeer/backend/fo_domain/draw/lua/DrawRedisLuaUtil.java
  src/main/java/com/softeer/backend/fo_domain/draw/lua/RedisConfigForLua.java
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawService.java
  src/main/java/com/softeer/backend/fo_domain/draw/service/DrawSettingManager.java
  src/test/java/com/softeer/backend/fo_domain/draw/service/DrawServiceTest.java
Labels: BE, Fix
